language: php
php:
  - 5.5
  - 5.6
  - nightly
  - hhvm
script:
  - phpunit -c app/
  - ./bin/phpcs --standard=./vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PSR2/ruleset.xml src/
  - ./bin/phpmd src/ text cleancode, codesize, controversial, design
  - ./bin/phpcpd src/
before_script:
  - composer self-update
  - composer install