services:
  student_service:
      class:  AppBundle\Services\StudentService
      arguments: [ "@=service('doctrine').getManager().getRepository('AppBundle:Student')" ]
  student_path_command:
      class: AppBundle\Command\StudentPathCommand
      arguments: [ @student_service ]
      tags:
        -  { name: console.command }