services:
  student_service:
      class:  AppBundle\Services\StudentService
      arguments: [ @doctrine.orm.entity_manager ]
  student_path_command:
      class: AppBundle\Command\StudentPathCommand
      arguments: [ @student_service ]
      tags:
        -  { name: console.command }